version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      # VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN}"
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_SITE_TITLE: "Project"
      WORDPRESS_SITE_URL: "https://${DOCKER_DEV_DOMAIN}" 
      WORDPRESS_DB_PASSWORD: mats
      WORDPRESS_DB_NAME: cpdb
    ports:
      - 127.0.0.1:8005:80 # Expose http and https
      - 448:443
    networks:
      - wordpress-network
      #- back
  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 127.0.0.1:3308:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: cpdb
      MYSQL_ROOT_PASSWORD: mats
    networks:
      - wordpress-network
      #- back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mats
      MYSQL_USERNAME: maestrom4
    networks:
      - wordpress-network
      #- back
networks:
  wordpress-network:
      driver: bridge
  #back:
volumes:
  db_data:

# version: '2'
# services:
#   wordpress:
#     image: wordpress:latest # https://hub.docker.com/_/wordpress/
#     ports:
#       - 127.0.0.1:81:80 # change ip if required
#     volumes:
#       - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#       - ./wp-app:/var/www/html # Full wordpress project
#       #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
#       #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
#     environment:
#       WORDPRESS_DB_HOST: db
#       WORDPRESS_DB_NAME: cpdb
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: mats_123456
#     depends_on:
#       - db
#     networks:
#       - wordpress-network
#   db:
#     image: mariadb:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
#     # ports:
#     #   - 127.0.0.1:3306:3306 # change ip if required
#     volumes:
#       - ./mysql-init:/var/lib/mysql:rw
#       - ./mysql-init/locations_schema.sql:/docker-entrypoint-initdb.d/locations_schema.sql:ro
#       # - ./wp-data:/docker-entrypoint-initdb.d
#     environment:
#       MYSQL_DATABASE: cpdb
#       MYSQL_ROOT_PASSWORD: mats_123456
#     networks:
#       - wordpress-network
#   phpmyadmin:
#     depends_on:
#       - db
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     ports:
#       - 8081:80
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: mats_123456
#     networks:
#       - wordpress-network
# networks:
#   wordpress-network:
#       driver: bridge

